const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),{File}=require('node:buffer'),{webcrypto}=require('node:crypto');
function setup(){const data=new Map([['igcseUserState','old-learning'],['igcseWritingDrafts','old-writing'],['igcseResources','old-resources']]);let docs=[],failWrite=false;const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>{if(failWrite&&k==='igcseWritingDrafts'){failWrite=false;throw Error('quota');}data.set(k,v);},removeItem:k=>data.delete(k)};const w={userState:{learnedTopics:[],questionStats:{},globalStats:{totalAnswered:2,totalCorrect:1}},IGCSE_CATALOG:{subjects:['math'],topic:(s,id)=>id==='a'?{subject:s}:null},IGCSE_MATERIALS:{all:async()=>docs,replaceAll:async items=>{docs=items;}}};vm.runInNewContext(fs.readFileSync('data/learning_backup.js','utf8'),{window:w,document:{readyState:'loading',addEventListener(){}},TextEncoder,localStorage:storage});vm.runInNewContext(fs.readFileSync('data/full_backup.js','utf8'),{window:w,document:{readyState:'loading',addEventListener(){}},TextEncoder,Uint8Array,File,Blob,URL,crypto:webcrypto,atob,btoa,localStorage:storage,Map,Set});return {w,storage,data,setDocs:items=>docs=items,getDocs:()=>docs,failNext:()=>failWrite=true};}
const fixture=()=>({format:'igcse-full-backup-v1',learning:{learnedTopics:[],questionStats:{},globalStats:{totalAnswered:4,totalCorrect:3}},writing:{email:{task:'Task',draft:'My draft',before:''}},resources:{math:{links:[{title:'Resource',url:'https://example.com'}],notes:[]}},materials:[]});
test('practice responses roundtrip in full backup and reject malformed or oversized drafts',async()=>{const {w}=setup(),f=fixture();f.learning.writtenPractice={question:{answer:'An original response.',updatedAt:1}};const parsed=await w.IGCSE_FULL_BACKUP.parse(JSON.stringify(f));assert.equal(parsed.learning.state.writtenPractice.question.answer,'An original response.');for(const writtenPractice of [{question:{answer:'x'.repeat(12001),updatedAt:1}},{question:{answer:'Text',updatedAt:-1}},Object.fromEntries(Array.from({length:101},(_,i)=>['q'+i,{answer:'Text',updatedAt:1}]))])await assert.rejects(w.IGCSE_FULL_BACKUP.parse(JSON.stringify({...f,learning:{...f.learning,writtenPractice}})));});
test('full backup rejects unsupported format, prototype keys, corrupt attachments and unsafe resource links before mutation',async()=>{const {w,data}=setup(),api=w.IGCSE_FULL_BACKUP;const f=fixture();assert.equal((await api.parse(JSON.stringify(f))).summary.drafts,1);for(const value of [{...f,format:'other'},{...f,resources:{math:{links:[{title:'bad',url:'javascript:alert(1)'}],notes:[]}}},{...f,materials:[{id:'bad'}]}])await assert.rejects(api.parse(JSON.stringify(value)));assert.throws(()=>api.safeJSON('{"__proto__":{}}'));assert.equal(data.get('igcseUserState'),'old-learning');});
test('attachment content and metadata survive portable roundtrip with checksum verification',async()=>{const {w,data,setDocs}=setup();data.set('igcseWritingDrafts',JSON.stringify(fixture().writing));data.set('igcseResources','{}');setDocs([{id:'one',subject:'math',kind:'textbook',ext:'txt',filename:'one.txt',title:'One',code:'0580',year:'2027',tier:'Core',createdAt:1,topicIds:['a'],pages:[{page:null,text:'Example'}],blob:new File(['Example'],'one.txt',{type:'text/plain'}),analysis:null}]);const text=await w.IGCSE_FULL_BACKUP.create(),p=await w.IGCSE_FULL_BACKUP.parse(text);assert.equal(await p.documents[0].blob.text(),'Example');assert.equal(p.documents[0].topicIds[0],'a');const corrupt=JSON.parse(text);corrupt.materials[0].data=btoa('Changed');await assert.rejects(w.IGCSE_FULL_BACKUP.parse(JSON.stringify(corrupt)));});
test('restore compensates all stores after a quota failure and refuses an active exam',async()=>{const {w,data,setDocs,getDocs,failNext}=setup();setDocs([{id:'old'}]);const p=await w.IGCSE_FULL_BACKUP.parse(JSON.stringify(fixture()));failNext();await assert.rejects(w.IGCSE_FULL_BACKUP.apply(p),/quota/);assert.equal(data.get('igcseUserState'),'old-learning');assert.equal(data.get('igcseWritingDrafts'),'old-writing');assert.equal(getDocs()[0].id,'old');w.userState.mockExams={activePractice:{}};await assert.rejects(w.IGCSE_FULL_BACKUP.apply(p));assert.equal(getDocs()[0].id,'old');});

test('vocabulary reinforcement records roundtrip and reject invalid mastery or counters',async()=>{const {w}=setup(),f=fixture(),r={wrong:2,correct:1,stage:0,lastQualifiedAt:0,nextReviewAt:1,lastSeenAt:1,mastered:false,flagged:true};f.learning.vocabArcade={records:{'cet4::improve':r}};assert.equal((await w.IGCSE_FULL_BACKUP.parse(JSON.stringify(f))).learning.state.vocabArcade.records['cet4::improve'].wrong,2);for(const bad of [{...r,stage:4},{...r,wrong:-1},{...r,flagged:'yes'}])await assert.rejects(w.IGCSE_FULL_BACKUP.parse(JSON.stringify({...f,learning:{...f.learning,vocabArcade:{records:{word:bad}}}})));});
