const test=require('node:test'),assert=require('node:assert/strict');
const {analyse,ground,validate,createServer}=require('../server/material_ai.cjs');
const topics=[{topicId:'math_number_01',title:'Numbers',chapter:'1'}],body={subject:'math',ext:'txt',filename:'notes.txt',pages:[{page:null,text:'Fractions and decimals are rational numbers.'}],fileData:'data:text/plain;base64,RnJhY3Rpb25z',code:'0580',year:'2025-2027'};
test('AI sends only explicit source data with server key and validates cited candidates',async()=>{let sent;const result=await analyse(body,{key:'test-private-key',topics,fetcher:async(url,options)=>{sent=JSON.parse(options.body);assert.equal(url,'https://api.openai.com/v1/responses');assert.equal(options.headers.Authorization,'Bearer test-private-key');return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify({summary:'练习分数',steps:['复习后练习'],topics:[{topicId:'math_number_01',reason:'有分数内容',quote:'Fractions and decimals',page:null},{topicId:'foreign',reason:'无效',quote:'Fractions',page:null}]})}]}]})};}});assert.equal(sent.store,false);assert.equal(sent.text.format.strict,true);assert.equal(sent.input[0].content.length,1);assert.equal(result.topics.length,1);assert.equal(result.topics[0].verified,true);assert.ok(!JSON.stringify(result).includes('test-private-key'));});
test('fabricated pages and quotes remain explicitly unverified; unknown topics removed',()=>{const a=ground({summary:'x',steps:[],topics:[{topicId:topics[0].topicId,reason:'x',quote:'Invented quote here',page:7}]},body,topics);assert.equal(a.topics[0].verified,false);assert.throws(()=>validate({...body,pages:[{page:-1,text:'x'}]},topics));assert.throws(()=>validate({...body,ext:'html'},topics));assert.throws(()=>validate({...body,fileData:'https://example.com/private'},topics));});
test('local service refuses cross-origin calls and missing credentials',async()=>{const server=createServer({key:'',topicsFor:()=>topics});await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const url='http://127.0.0.1:'+server.address().port;const status=await (await fetch(url+'/api/ai/status')).json();assert.equal(status.configured,false);assert.ok(!JSON.stringify(status).includes('key'));assert.equal((await fetch(url+'/api/materials/analyse',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:'{}'})).status,403);const r=await fetch(url+'/api/materials/analyse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});assert.equal(r.status,503);assert.match((await r.json()).error,/尚未启用/);assert.equal((await fetch(url+'/server/material_ai.cjs')).status,403);}finally{await new Promise(r=>server.close(r));}});
test('DeepSeek uses its endpoint and extracted PDF text, without unsupported file inputs',async()=>{let sent;const result=await analyse({...body,ext:'pdf',fileData:'data:application/pdf;base64,'+Buffer.from('%PDF-1.4 fixture').toString('base64')},{provider:'deepseek',key:'fixture-secret',topics,fetcher:async(url,options)=>{assert.equal(url,'https://api.deepseek.com/responses');sent=JSON.parse(options.body);return {ok:true,json:async()=>({output:[{content:[{type:'output_text',text:JSON.stringify({summary:'x',steps:[],topics:[{topicId:topics[0].topicId,reason:'x',quote:'Fractions and decimals',page:null}]})}]}]})};}});assert.equal(sent.model,'deepseek-flash');assert.equal(sent.input[0].content.length,1);assert.equal(sent.reasoning.effort,'none');assert.equal(sent.text.format.strict,undefined);assert.equal(result.topics[0].verified,true);});
test('DeepSeek refuses unreadable PDFs and unsupported vision models before any request',async()=>{let calls=0;const opts={provider:'deepseek',key:'fixture',topics,fetcher:async()=>{calls++;}};await assert.rejects(analyse({...body,ext:'pdf',pages:[],fileData:'data:application/pdf;base64,'+Buffer.from('%PDF-1.4').toString('base64')},opts),/需要可读取/);await assert.rejects(analyse({...body,ext:'png',fileData:'data:image/png;base64,iVBORw=='},{...opts,model:'deepseek-v4-pro'}),/deepseek-flash/);assert.equal(calls,0);});
test('provider errors expose only safe actionable messages',async()=>{await assert.rejects(analyse(body,{provider:'deepseek',key:'fixture',topics,fetcher:async()=>({ok:false,status:402,json:async()=>({error:'private provider response'})})}),/额度不足/);const {config}=require('../server/material_ai.cjs');assert.deepEqual(config({IGCSE_AI_PROVIDER:'deepseek',DEEPSEEK_API_KEY:'fixture'}),{provider:'deepseek',key:'fixture',model:'deepseek-flash'});assert.throws(()=>config({IGCSE_AI_PROVIDER:'unknown'}));});
