const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 console.log('discovery',width);const before=await page.evaluate(()=>JSON.stringify(userState));
 const menu=await page.locator('#mainNav .nav-btn:not([hidden])').evaluateAll(bs=>bs.map(b=>b.dataset.page));
 assert.equal(await page.locator('#mainNav [data-shell-group]').count(),7);assert.equal(menu.indexOf('page-english')+1,menu.indexOf('page-writing'));
 await page.locator('#platformSettings').click();await page.locator('#navOrderSettings > summary').click();await page.locator('[data-order-id="page-writing"] [data-move=up]').click();await page.reload();await page.locator('#navOrderSettings > summary').click();const moved=await page.locator('#mainNav .nav-btn:not([hidden])').evaluateAll(bs=>bs.map(b=>b.dataset.page));assert.equal(moved.indexOf('page-writing')+1,moved.indexOf('page-english'));await page.locator('#resetNavOrder').click();await page.locator('#navOrderSettings > summary').click();
 // Hint use is preserved, separated from mistakes and completed only by independent success.
 const qid=await page.evaluate(()=>IGCSE_CATALOG.questions.find(q=>q.subject==='math'&&q.type==='choice').id);
 await page.evaluate(id=>startSessionFromIds([id],'normal',{subject:'math'}),qid);await page.locator('#questionArea [data-hint-button]').click();assert.equal(await page.locator('#questionArea [data-hint-text]').isVisible(),true);
 const correct=await page.evaluate(id=>{const q=findQuestion(id);return q.options.indexOf(q.answer);},qid);await page.locator('#questionArea .opt-btn').nth(correct).click();assert.equal(await page.locator('#questionArea [data-hint-button]').isDisabled(),true);assert.equal(await page.evaluate(id=>userState.hintReviews[id].status,qid),'pending');assert.equal(await page.evaluate(id=>userState.questionStats[id].assistedAnswered,qid),1);
 await page.locator('[data-page="page-mistake"]').click();await page.locator('#mistakeStats [data-ws-subject="math"]').click();await page.locator('#reviewKind').selectOption('hint');assert.equal(await page.locator('[data-review-qid="'+qid+'"]').count(),1);
 await page.reload();await page.locator('[data-review-start="'+qid+'"]').click();await page.locator('#questionArea .opt-btn').nth(correct).click();assert.equal(await page.evaluate(id=>userState.hintReviews[id].status,qid),'complete');
 await page.evaluate(id=>startSessionFromIds([id],'normal',{subject:'math',noHints:true}),qid);assert.equal(await page.locator('#questionArea [data-hint-button]').count(),0);
 // Free practice keeps the teaching status unstarted, while recommendations remain separate.
 await page.evaluate(()=>{IGCSE_CURRICULUM.setProfile('math',{qualification:'IGCSE',code:'0580',examYear:2027});setCurrentSubjectSafe('math');});await page.locator('[data-page="page-practice"]').click();await page.locator('#practiceSchoolScope').selectOption('all');assert.ok(await page.locator('[data-start-topic]').count()>2);assert.match(await page.locator('[data-start-topic]').last().textContent(),/未教/);
 await page.locator('[data-page="page-chapters"]').click();await page.locator('#ceSub').selectOption('math');const qt=await page.evaluate(id=>IGCSE_CATALOG.topic('math',findQuestion(id).topicId),qid);await page.locator('#ceCh').selectOption(qt.chapter);await page.locator('#ceTopic').selectOption(qt.topicId);await page.locator('#ceStartTopic').click();assert.equal(await page.locator('#ceBody [data-hint-button]').count(),1);await page.locator('#ceBody [data-hint-button]').click();await page.locator('#ceBody [data-ans]').first().click();assert.equal(await page.locator('#ceBody [data-hint-button]').isDisabled(),true);await page.locator('#ceTabs [data-m="chapterTest"]').click();assert.equal(await page.locator('#ceBody [data-hint-button]').count(),0);
 for(const id of ['page-curriculum','page-path','page-progress']){await page.locator('[data-page="'+id+'"]').click();const root=page.locator('#'+id);assert.equal(await root.locator('[data-browse-toolbar] [data-ws-subject]').count(),7);await root.locator('[data-browse-chapter]').selectOption('');await root.locator('[data-browse-search]').fill('不存在的章节zz');assert.match(await root.locator('[data-browse-count]').textContent(),/^0 \/ /);await root.locator('[data-browse-search]').fill('');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'browse overflow '+id+' '+width);}
 await page.locator('[data-page="page-vocab"]').click();await page.locator('#vocabBrowse [data-ws-subject="english"]').click();const total=await page.evaluate(()=>IGCSE_WORKSPACE.gamePool().length);assert.ok(total>=300);await page.locator('#vocabChapter').selectOption('Reading');assert.ok(await page.evaluate(()=>IGCSE_WORKSPACE.gamePool().length)>=30);assert.ok(await page.locator('#vocabResults .ws-word').count()<=24);await page.locator('[data-word-page=next]').click();assert.match(await page.locator('#vocabResults').textContent(),/第 2 \/ /);await page.locator('#vocabGameEn2Zh').click();assert.equal(await page.evaluate(()=>vocabGame.limit),10);assert.ok(await page.evaluate(()=>vocabGame.pool.every(v=>(v.chapters||[v.chapter]).includes('Reading'))));await page.screenshot({path:path.join(results,'expanded-vocab-'+width+'.png'),fullPage:true});
 for(const [subject,needle] of [['business','利益相关者'],['computer_science','参照完整性'],['english','主谓']]){await page.locator('[data-page="page-quickref"]').click();await page.locator('#quickrefContent [data-ws-subject="'+subject+'"]').click();await page.locator('#quickrefSearch').fill(needle);await page.locator('#quickrefResults .ws-reference').first().waitFor();assert.ok(await page.locator('#quickrefResults .ws-reference').count()>0,'quickref '+subject+' / '+needle+' / '+await page.locator('#quickrefChapter').inputValue());}
 await page.locator('[data-page="page-achievements"]').click();assert.equal(await page.locator('#page-achievements.active').count(),1);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(results,'learning-achievements-'+width+'.png'),fullPage:true});
 assert.deepEqual(await page.evaluate(()=>{const ids=[...document.querySelectorAll('[id]')].map(e=>e.id);return ids.filter((id,i)=>ids.indexOf(id)!==i);}),[],'unique element IDs');
 await page.evaluate(json=>{userState=window.userState=JSON.parse(json);saveUserState(userState);localStorage.removeItem('igcseBrowsePreferences');localStorage.removeItem('igcseNavOrder');},before);await page.reload();await page.locator('#dashboard-nav').click();
};
