const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 await page.evaluate(()=>{window.__savedSpeak=window.speakIGCSE;window.__spoken=[];window.speakIGCSE=text=>{window.__spoken.push(text);return Promise.resolve({ok:true,american:true});};document.querySelector('[data-page=page-english]').click();});
 await page.locator('#englishSkill').selectOption('listening');await page.locator('[data-eng-topic]').first().click();await page.locator('#englishMediaPlay').waitFor();assert.match(await page.locator('#englishTopicNotes').textContent(),/Read the questions/);await page.evaluate(()=>setIGCSEGlobalLang('exam'));assert.equal(await page.locator('#englishTopicNotes details').count(),0);await page.evaluate(()=>setIGCSEGlobalLang('bilingual'));assert.equal(await page.locator('#englishTopicNotes details').count(),1);assert.ok(await page.evaluate(()=>__spoken.length)>0);
 await page.locator('#engTopicPractice').click();await page.evaluate(()=>startSessionFromIds(['eng_l1'],'normal',{subject:'english',topicId:'eng_esl_listening'}));await page.locator('#questionArea #englishMediaPlay').waitFor();assert.match(await page.locator('#questionArea .q-body').textContent(),/请听音源/);assert.equal(await page.evaluate(()=>practiceSession.hints?.[practiceSession.order[practiceSession.idx]]),undefined);await page.locator('#questionArea .english-media-panel summary').click();await page.waitForFunction(()=>practiceSession.hints?.[practiceSession.order[practiceSession.idx]]===true);
 await page.evaluate(()=>document.querySelector('[data-page=page-english]').click());await page.locator('#englishSkill').selectOption('speaking');await page.locator('[data-eng-topic]').first().click();await page.locator('#englishRecordStart').waitFor();
 await page.evaluate(()=>{window.__gum=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError');};});await page.locator('#englishRecordStart').click();await page.locator('#englishMediaStatus').filter({hasText:'麦克风被拒绝'}).waitFor();assert.equal(await page.locator('#englishRecordStart').isEnabled(),true);
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async opts=>{const stream=await __gum(opts);window.__tracks=stream.getTracks();return stream;};});await page.locator('#englishRecordStart').click();await page.locator('#englishRecordStop').waitFor({state:'visible'});await page.waitForFunction(()=>!document.getElementById('englishRecordStop').disabled);await page.waitForTimeout(350);await page.locator('#englishRecordStop').click();await page.locator('#englishRecording').waitFor({state:'visible'});assert.ok(await page.locator('#englishRecording').getAttribute('src'));assert.equal(await page.evaluate(()=>__tracks.every(t=>t.readyState==='ended')),true);
 await page.screenshot({path:path.join(results,'english-speaking-'+width+'.png'),fullPage:true});await page.locator('#englishRecordStart').click();await page.waitForFunction(()=>!document.getElementById('englishRecordStop').disabled);await page.evaluate(()=>document.querySelector('[data-page=page-dashboard]').click());assert.equal(await page.evaluate(()=>__tracks.every(t=>t.readyState==='ended')),true);
 await page.evaluate(()=>{IGCSE_SHELL.setUI('en');document.querySelector('[data-page=page-english]').click();});assert.match(await page.locator('#englishCenterContent').textContent(),/mission map/);await page.evaluate(()=>IGCSE_SHELL.setUI('zh'));assert.match(await page.locator('#englishCenterContent').textContent(),/课程地图/);
 await page.evaluate(()=>{document.querySelector('[data-page=page-textbook]').click();document.querySelector('#learningCenterTools [data-ws-subject=english]').click();});assert.equal(await page.locator('[data-learning-zone]').count(),6);assert.equal(await page.locator('#topicList [data-topic-id]').count(),18);await page.locator('[data-learning-zone=Speaking]>summary').click();assert.equal(await page.locator('[data-learning-zone=Speaking] [data-topic-id]').first().isVisible(),true);await page.screenshot({path:path.join(results,'english-learning-zones-'+width+'.png'),fullPage:true});
 if(width<768){const size=await page.locator('#mobileNavigation button').first().evaluate(el=>({height:el.getBoundingClientRect().height,font:parseFloat(getComputedStyle(el).fontSize)}));assert.ok(size.height>=62);assert.ok(size.font>=13);}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.evaluate(()=>{window.speakIGCSE=__savedSpeak;navigator.mediaDevices.getUserMedia=__gum;});await page.reload();console.log('English audio, microphone denial/recording/release, language and mobile controls '+width);
};
