const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
module.exports=async(page,width,results)=>{
 const original=await page.evaluate(()=>IGCSE_FULL_BACKUP.create());
 await page.evaluate(async()=>{userState.globalStats.totalAnswered=7;userState.globalStats.totalCorrect=5;saveUserState(userState);localStorage.setItem('igcseWritingDrafts',JSON.stringify({email:{task:'A test invitation',draft:'Please join our club on Friday.',before:'Please join us.',updatedAt:new Date().toISOString()}}));localStorage.setItem('igcseResources',JSON.stringify({math:{links:[{title:'Official syllabus',url:'https://www.cambridgeinternational.org/'}],notes:[{title:'Revision',body:'Use a multiplier.',img:'',marks:[]}]}}));await IGCSE_MATERIALS.put({id:'portable-fixture',subject:'math',kind:'textbook',title:'Portable textbook',filename:'portable.txt',ext:'txt',code:'0580',year:'2027',tier:'unspecified',createdAt:Date.now(),topicIds:['course_math_reverse'],pages:[{page:null,text:'Original portable material.'}],blob:new File(['Original portable material.'],'portable.txt',{type:'text/plain'}),analysis:null});switchPage('page-backup');});
 const event=page.waitForEvent('download');await page.locator('#fullBackupDownload').click();const file=await event;assert.equal(file.suggestedFilename(),'igcse-full-backup.json');const bytes=fs.readFileSync(await file.path());const bundle=JSON.parse(bytes);assert.equal(bundle.materials.length,1);assert.equal(bundle.writing.email.draft,'Please join our club on Friday.');
 const context=await page.context().browser().newContext({viewport:{width,height:900},acceptDownloads:true}),fresh=await context.newPage();try{await fresh.route('**/*',route=>route.request().url().startsWith(new URL(page.url()).origin)?route.continue():route.abort());await fresh.goto(new URL(page.url()).origin+'/#page-dashboard');await fresh.evaluate(()=>switchPage('page-backup'));assert.match(await fresh.locator('#pageLocation').textContent(),/学习备份/);await fresh.locator('#fullBackupFile').setInputFiles({name:'corrupt.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({...bundle,materials:[{...bundle.materials[0],sha256:'0'.repeat(64)}]}))});await fresh.waitForFunction(()=>document.getElementById('fullBackupStatus').textContent.includes('损坏'));assert.equal(await fresh.locator('#fullBackupConfirm').isDisabled(),true);
 await fresh.locator('#fullBackupFile').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:bytes});await fresh.waitForFunction(()=>!document.getElementById('fullBackupConfirm').disabled);assert.match(await fresh.locator('#fullBackupStatus').textContent(),/1 份附件/);await fresh.locator('#fullBackupConfirm').check();const snapshot=fresh.waitForEvent('download');await Promise.all([fresh.waitForNavigation({waitUntil:'domcontentloaded'}),fresh.locator('#fullBackupRestore').click()]);assert.equal((await snapshot).suggestedFilename(),'igcse-before-full-restore.json');await fresh.locator('#dbMock').waitFor();assert.equal(await fresh.evaluate(()=>userState.globalStats.totalAnswered),7);assert.equal(await fresh.evaluate(()=>JSON.parse(localStorage.getItem('igcseWritingDrafts')).email.draft),'Please join our club on Friday.');assert.equal(await fresh.evaluate(()=>JSON.parse(localStorage.getItem('igcseResources')).math.notes[0].body),'Use a multiplier.');assert.equal(await fresh.evaluate(async()=>await (await IGCSE_MATERIALS.get('portable-fixture')).blob.text()),'Original portable material.');await fresh.evaluate(()=>switchPage('page-backup'));await fresh.screenshot({path:path.join(results,'full-backup-'+width+'.png'),fullPage:true});assert.equal(await fresh.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 }finally{await context.close();}
 await page.evaluate(async original=>{await IGCSE_FULL_BACKUP.apply(await IGCSE_FULL_BACKUP.parse(original));},original);await page.reload();console.log('portable backup '+width);
};
