const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 const before=await page.evaluate(()=>JSON.stringify(userState));const nav=async id=>{await page.evaluate(id=>document.querySelector('[data-page="'+id+'"]').click(),id);await page.locator('#'+id+'.active').waitFor();};
 // Missing content has a retry path and does not strand navigation.
 let failed=false;await page.route('**/data/grammar_bank.json',route=>{if(!failed){failed=true;return route.fulfill({status:200,body:'invalid JSON'});}return route.continue();});await nav('page-grammar');await page.getByRole('button',{name:'重试加载',exact:true}).waitFor();await page.getByRole('button',{name:'重试加载',exact:true}).click();await page.locator('#grammarUnit').waitFor();await page.unroute('**/data/grammar_bank.json');assert.equal(await page.locator('#page-grammar .grammar-island').count(),8);await page.locator('#grammarMapNext').click();assert.match(await page.locator('#grammarBody').textContent(),/第 2 \/ 3 页/);
 await page.locator('#grammarUnit').selectOption('noun-article');await page.locator('#grammarDiagnostic').click();const q=await page.evaluate(()=>IGCSE_GRAMMAR.choices().find(q=>q.unitId==='noun-article'));const wrong=q.options.findIndex(o=>o!==q.answer);await page.locator('[data-grammar-answer="'+wrong+'"]').click();assert.match(await page.locator('#grammarFeedback').textContent(),/已加入错点/);assert.equal(await page.evaluate(id=>userState.grammarTraining.records[id].attempts,q.id),1);
 await page.locator('#grammarReview').click();assert.match(await page.locator('#grammarBody').textContent(),/1 \/ 1/);await page.locator('[data-grammar-answer="'+q.options.indexOf(q.answer)+'"]').click();assert.equal(await page.evaluate(id=>userState.grammarTraining.records[id].needsReview,q.id),false);
 await page.locator('#grammarPractice').click();for(let i=0;i<3;i++){const answer=await page.evaluate(i=>IGCSE_GRAMMAR.units()[0].questions[i].answer,i);await page.locator('[data-grammar-answer]').filter({hasText:answer}).first().click();await page.locator('#grammarNext').click();}
 await page.locator('#grammarAnswer').fill('I bought an umbrella for the trip.');await page.locator('#grammarReference').click();assert.match(await page.locator('#grammarFeedback').textContent(),/允许其他合理答案/);await page.locator('[data-grammar-self=yes]').click();assert.equal(await page.evaluate(()=>userState.grammarTraining.records['gr-noun-article-correct'].attempts),0);await page.locator('#grammarNext').click();await page.locator('#grammarAnswer').fill('The useful book is the one that I bought.');await page.locator('#grammarReference').click();await page.locator('[data-grammar-self=yes]').click();await page.locator('#grammarTransfer').click();assert.equal(await page.locator('#page-writing').isVisible(),true);assert.match(await page.locator('#grammarWritingPrompt').textContent(),/语法迁移/);
 await nav('page-grammar');await page.locator('#grammarGames').click();await page.locator('[data-arcade-choice]').first().waitFor();assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().queue.every(q=>q.unitId==='noun-article')),true);await page.evaluate(()=>IGCSE_ARCADE.stop());await page.locator('#arcadeGrammarTopic').selectOption('conditionals');await page.locator('[data-arcade-mode=grammar]').click();assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().queue.every(q=>q.unitId==='conditionals')),true);await page.evaluate(()=>IGCSE_ARCADE.stop());
 // All catalogue topics are visible regardless of school status; normal practice stays available.
 await page.evaluate(()=>{setCurrentSubjectSafe('math');IGCSE_CURRICULUM.setProfile('math',{qualification:'IGCSE',code:'0580',examYear:2027,foundation:false});const t=IGCSE_CURRICULUM.ordered('math')[0];IGCSE_CURRICULUM.setTopic('math',t.topicId,'unstarted',1);});await nav('page-chapters');await page.locator('#ceCh').selectOption('');assert.equal(await page.locator('#ceCh').inputValue(),'');assert.ok(await page.locator('[data-topic]').count()<=8);const math=await page.evaluate(()=>IGCSE_CURRICULUM.ordered('math').length);assert.match(await page.locator('#ceBody').textContent(),new RegExp('找到 '+math+' 个主题'));
 const t=await page.evaluate(()=>IGCSE_CURRICULUM.ordered('math').find(t=>IGCSE_CATALOG.questionsFor('math',t.topicId).some(q=>q.type==='choice')));await page.locator('#ceSearch').fill(t.topicId);await page.locator('#ceSearchButton').click();assert.match(await page.locator('#ceBody').textContent(),/未教/);await page.locator('[data-topic="'+t.topicId+'"]').click();assert.match(await page.locator('.chapter-access-note').textContent(),/均可自主练习/);await page.locator('#ceStartTopic').click();assert.ok(await page.locator('[data-ans]').count()>0);await page.locator('[data-m=overview]').click();
 await page.evaluate(id=>IGCSE_CURRICULUM.setTopic('math',id,'taught',1),t.topicId);assert.match(await page.locator('[data-topic="'+t.topicId+'"] .chapter-status').textContent(),/已教/);await page.locator('#ceStatusFilter').selectOption('unstarted');assert.equal(await page.locator('[data-topic="'+t.topicId+'"]').count(),0);await page.locator('#ceAllChapters').click();await page.locator('#ceMore').click();assert.match(await page.locator('#ceBody').textContent(),/第 2 \//);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(results,'chapter-map-'+width+'.png'),fullPage:true});
 await nav('page-grammar');await page.locator('#grammarLevel').selectOption('application');assert.equal(await page.locator('#page-grammar .grammar-island').count(),3);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(results,'grammar-training-'+width+'.png'),fullPage:true});await nav('page-quickref');await page.locator('#quickrefContent [data-ws-subject=english]').click();await page.locator('#quickrefSearch').fill('');await page.locator('#quickrefChapter').selectOption('IGCSE 核心语法速查');assert.match(await page.locator('#quickrefResults').textContent(),/13 条要点/);await page.locator('#quickrefSearch').fill('间接引语');assert.match(await page.locator('#quickrefResults').textContent(),/1 条要点/);await page.locator('#quickrefSearch').fill('');await page.locator('#quickrefChapter').selectOption('');assert.match(await page.locator('#quickrefResults').textContent(),/30 条要点/);await page.screenshot({path:path.join(results,'grammar-quickref-'+width+'.png'),fullPage:true});
 const archive=await page.evaluate(()=>IGCSE_FULL_BACKUP.create());assert.ok(await page.evaluate(async raw=>Boolean((await IGCSE_FULL_BACKUP.parse(raw)).learning.state.grammarTraining),archive));
 await page.evaluate(before=>{for(const k of Object.keys(userState))delete userState[k];Object.assign(userState,JSON.parse(before));saveUserState(userState);},before);await page.reload();console.log('grammar topics, production, game filters and open chapter paths '+width);
};
