const assert=require('node:assert/strict');
const JSZip=require('jszip');
async function docx(){const zip=new JSZip();zip.file('[Content_Types].xml','<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.file('_rels/.rels','<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.file('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>Fractions and decimals homework.</w:t></w:r></w:p></w:body></w:document>');return zip.generateAsync({type:'nodebuffer'});}
function pdf(){const stream='BT /F1 12 Tf 40 100 Td (Fractions and decimals) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 200] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream'];let s='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(s));s+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const start=Buffer.byteLength(s);s+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+start+'\n%%EOF';return Buffer.from(s);}
module.exports=async function materialFlows(page,width,results){
 await page.route('**/api/ai/status',route=>route.fulfill({json:{configured:true}}));
 await page.locator('#materials-nav').click();
 const initial=await page.evaluate(()=>JSON.stringify({mastery:window.userState.mastery,questionStats:window.userState.questionStats,topicStats:window.userState.topicStats}));
 for(const subject of ['math','physics','chemistry','dt','business','computer_science','english']){
  await page.locator('#subjectSelect').selectOption(subject);await page.locator('#materialSave').waitFor();
  await page.locator('#materialKind').selectOption(subject==='english'?'homework':'textbook');
  await page.locator('#materialFile').setInputFiles({name:subject+' <script>.txt',mimeType:'text/plain',buffer:Buffer.from('Fractions and decimals <img src=x onerror=alert(1)>')});await page.locator('#materialSave').click();await page.waitForFunction(()=>!document.querySelector('#materialSave').disabled);assert.match(await page.locator('#materialStatus').textContent(),/已保存并读取/);assert.equal(await page.locator('[data-material]').count(),1);
 }
 // Uploading does not create learning evidence (subject selection may update last subject).
 assert.equal(await page.evaluate(()=>JSON.stringify({mastery:window.userState.mastery,questionStats:window.userState.questionStats,topicStats:window.userState.topicStats})),initial);
 await page.locator('#subjectSelect').selectOption('math');await page.locator('[data-material]').waitFor();await page.locator('[data-material]').click();await page.locator('#materialDetail summary').click();await page.locator('#materialText').waitFor();assert.match(await page.locator('#materialText').inputValue(),/<img src=x/);assert.equal(await page.locator('#materialDetail img').count(),0);
 await page.locator('.material-topics input').first().check();await page.locator('#materialLinkSave').click();await page.locator('[data-material-practice]').waitFor();const topic=await page.locator('[data-material-practice]').getAttribute('data-material-practice');await page.locator('[data-material-practice]').click();assert.ok(await page.evaluate(t=>practiceSession.order.every(id=>findQuestion(id).subject==='math'&&findQuestion(id).topicId===t),topic));
 await page.locator('#materials-nav').click();await page.locator('[data-material]').waitFor();await page.reload();await page.locator('[data-material]').waitFor();assert.equal(await page.locator('[data-material]').count(),1);
 for(const [name,mime,buffer] of [['chapter.pdf','application/pdf',pdf()],['homework.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document',await docx()]]){await page.locator('#materialFile').setInputFiles({name,mimeType:mime,buffer});await page.locator('#materialSave').click();await page.waitForFunction(()=>!document.querySelector('#materialSave').disabled);assert.match(await page.locator('#materialStatus').textContent(),/已保存并读取/);const b=page.locator('#materialList article').filter({hasText:name}).locator('[data-material]');await b.click();await page.locator('#materialDetail summary').click();await page.locator('#materialText').waitFor();assert.match(await page.locator('#materialText').inputValue(),/Fractions and decimals/);if(name.endsWith('.pdf'))assert.match(await page.locator('#materialText').inputValue(),/第 1 页/);}
 const fixture={summary:'分数与小数',steps:['复习后练习'],topics:[{topicId:topic,reason:'资料包含分数',quote:'Fractions and decimals',page:null,verified:true}]};
 await page.route('**/api/materials/analyse',route=>{const body=route.request().postDataJSON();assert.equal(body.subject,'math');assert.ok(body.fileData.startsWith('data:'));return route.fulfill({json:fixture});});
 await page.locator('#materialAI').click();await page.locator('#materialAIStatus').filter({hasText:'分析完成'}).waitFor();assert.match(await page.locator('#materialAnalysis').textContent(),/文字引用已匹配/);await page.locator('[data-ai-topic]').click();assert.equal(await page.locator('[data-material-practice]').count(),0,'AI does not automatically confirm chapter links');await page.locator('#materialLinkSave').click();await page.locator('[data-material-practice]').waitFor();await page.unroute('**/api/materials/analyse');
 await page.locator('#materialFile').setInputFiles({name:'unsafe.html',mimeType:'text/html',buffer:Buffer.from('<script>alert(1)</script>')});await page.locator('#materialSave').click();await page.locator('#materialStatus').filter({hasText:'请选择 PDF'}).waitFor();assert.equal(await page.locator('[data-material]').count(),3);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'materials mobile overflow '+width);await page.screenshot({path:require('node:path').join(results,'materials-'+width+'.png'),fullPage:true});
 await page.locator('#materialDelete').click();await page.locator('#materialStatus').filter({hasText:'已删除'}).waitFor();assert.equal(await page.locator('[data-material]').count(),2);
 await page.locator('#materialKind').selectOption('homework');
 await page.locator('#materialFile').setInputFiles({name:'scan.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jZ1cAAAAASUVORK5CYII=','base64')});
 await page.locator('#materialSave').click();await page.waitForFunction(()=>!document.querySelector('#materialSave').disabled);assert.match(await page.locator('#materialStatus').textContent(),/扫描件或图片/);
 await page.locator('#materialFilter').selectOption('homework');await page.locator('#materialList article').filter({hasText:'scan.png'}).locator('[data-material]').click();await page.locator('#materialPreview img').waitFor();assert.equal(await page.locator('[data-material]').count(),1);
 await page.locator('#materialDetail summary').click();await page.locator('#materialText').fill('Scanned fractions homework');await page.locator('#materialTextSave').click();await page.locator('#materialStatus').filter({hasText:'已保存补充文字'}).waitFor();
 await page.locator('#materialDelete').click();await page.locator('#materialStatus').filter({hasText:'已删除'}).waitFor();await page.locator('#materialFilter').selectOption('all');await page.waitForFunction(()=>document.querySelectorAll('[data-material]').length===2);
 await page.locator('#dashboard-nav').click();
};
