const assert=require('node:assert/strict');
module.exports=async page=>{
 await page.locator('#dashboard-nav').click();const task=await page.evaluate(()=>IGCSE_DASHBOARD.day().tasks.find(t=>t.type==='material'));assert.ok(task,'confirmed links enter daily plan');
 await page.locator('[data-task="'+task.id+'"]').click();await page.locator('#materialLearningNext').waitFor();assert.equal(await page.evaluate(id=>IGCSE_DASHBOARD.day().completed.includes(id),task.id),false,'reading does not finish practice');
 await page.getByRole('button',{name:'查看来源资料',exact:true}).click();await page.locator('#materialDetail h3').waitFor();assert.equal(await page.locator('#materialDetail h3').textContent(),task.materialTitle);
 await page.locator('#dashboard-nav').click();await page.locator('[data-task="'+task.id+'"]').click();await page.getByRole('button',{name:'下一步：资料练习',exact:true}).click();
 const q=await page.evaluate(()=>findQuestion(practiceSession.order[0]));assert.equal(q.subject,task.subject);assert.equal(q.topicId,task.topic);if(q.type==='choice'){const wrong=q.options.findIndex(o=>o!==q.answer);await page.locator('#questionArea .opt-btn').nth(wrong).click();}else if(q.type==='number'){await page.locator('#numberInput').fill(String(Number(q.answer)===0?1:0));await page.locator('[data-act=number-check]').click();}else{await page.locator('#essayInput').fill('I need to review this topic.');await page.locator('[data-act=essay-check]').click();await page.locator('[data-self=no]').click();}assert.equal(await page.evaluate(id=>IGCSE_DASHBOARD.day().completed.includes(id),task.id),true);
 await page.locator('#dashboard-nav').click();await page.locator('[data-material-review="'+task.id+'"]').click();assert.ok(await page.evaluate(id=>practiceSession.mode==='srs'&&practiceSession.order.includes(id),q.id));
 await page.evaluate(async id=>{const d=await IGCSE_MATERIALS.get(id);d.topicIds=[];await IGCSE_MATERIALS.put(d);},task.materialId);await page.locator('#dashboard-nav').click();assert.equal(await page.evaluate(()=>IGCSE_DASHBOARD.day().tasks.filter(t=>t.type==='material').length),0);
 await page.reload();await page.locator('#dbMock').waitFor();assert.equal(await page.evaluate(()=>IGCSE_DASHBOARD.day().tasks.filter(t=>t.type==='material').length),0);
};
