const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 console.log('shell',width);await page.locator('#mainNav [data-shell-group]').first().waitFor({state:'attached'});
 assert.equal(await page.locator('#subjectSelect').isVisible(),false);assert.equal(await page.locator('#langToggle').isVisible(),false);assert.equal(await page.locator('#igcse-language-bar').count(),0);assert.equal(await page.locator('#mainNav [data-shell-group]').count(),7);
 const source=await page.evaluate(()=>JSON.stringify(userState));
 const group=page.locator((width<768?'#mobileNavigation':'#mainNav')+' [data-shell-group="english"]');await group.click();await page.locator('#mainNav [data-page="page-writing"]').click();assert.equal(await page.locator('#page-writing.active').count(),1);if(width<768)assert.equal(await page.locator('#learningSidebar').isVisible(),false);
 await page.locator('#writingDraft').fill('A draft that must survive interface and content language changes.');const draft=await page.locator('#writingDraft').inputValue();
 await page.locator('#languageSettings > summary').click();await page.locator('#interfaceLanguage').selectOption('en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#writingDraft').inputValue(),draft);assert.match(await page.locator('#mainNav [data-page="page-writing"]').textContent(),/Writing studio/);assert.equal(await page.locator('#sourceLanguageNotice').isVisible(),true);await page.screenshot({path:path.join(results,'english-interface-'+width+'.png'),fullPage:true});
 await page.locator('#contentLanguage').selectOption('exam');assert.equal(await page.evaluate(()=>IGCSE_GLOBAL_LANG),'exam');assert.equal(await page.locator('#writingDraft').inputValue(),draft);await page.locator('#languageSettings > summary').click();
 await page.reload();await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#writingDraft').inputValue(),draft);assert.equal(await page.evaluate(()=>igcseLang()),'exam');
 await page.locator((width<768?'#mobileNavigation':'#mainNav')+' [data-shell-group="learn"]').click();await page.locator('#mainNav [data-page="page-textbook"]').click();await page.locator('#learningCenterTools [data-ws-subject="physics"]').click();assert.equal(await page.evaluate(()=>currentSubject),'physics');const title=await page.locator('[data-topic-id]').first().textContent();assert.ok(title);await page.locator('[data-topic-id]').first().click();assert.equal(await page.locator('#topicContent').isVisible(),true);
 const before=await page.evaluate(()=>JSON.stringify(userState));await page.locator('#languageSettings > summary').click();await page.locator('#interfaceLanguage').selectOption('zh');await page.locator('#contentLanguage').selectOption('bilingual');await page.locator('#languageSettings > summary').click();assert.equal(await page.evaluate(()=>JSON.stringify(userState)),before,'language preferences do not alter learning evidence');assert.match(await page.locator('#mainNav [data-page="page-textbook"]').textContent(),/教材学习/);
 await page.locator((width<768?'#mobileNavigation':'#mainNav')+' [data-shell-group="tools"]').click();await page.locator('#mainNav [data-page="page-materials"]').click();assert.equal(await page.locator('#page-materials [data-shell-subjects] [data-ws-subject]').count(),7);await page.locator('#page-materials [data-ws-subject="math"]').click();assert.equal(await page.evaluate(()=>currentSubject),'math');
 await page.locator((width<768?'#mobileNavigation':'#mainNav')+' [data-shell-group="tools"]').click();await page.locator('#mainNav [data-page="page-vocab"]').click();assert.equal(await page.locator('[data-vocab-tab]').count(),3);assert.ok(await page.locator('#vocabResults details').count()<=8);if(await page.locator('#vocabResults [data-word-page=next]').isEnabled()){await page.locator('#vocabResults [data-word-page=next]').click();assert.match(await page.locator('#vocabResults').textContent(),/第 2 \/ /);}assert.equal(await page.locator('#vocabGamePanel').isVisible(),false);await page.locator('[data-vocab-tab=game]').click();assert.equal(await page.locator('#vocabResults').isVisible(),false);await page.locator('[data-vocab-tab=review]').click();assert.equal(await page.locator('#vocabReviewPanel').isVisible(),true);await page.locator('[data-vocab-tab=words]').click();
 await page.locator('#vocabBrowse [data-ws-subject="math"]').click();const word=await page.evaluate(()=>{const v=SUBJECT_VOCAB.find(v=>v.subject==='math');userState.vocabMistakes=[{...v,key:v.subject+'::'+v.en,srsStage:2,wrongCount:1,nextReviewAt:new Date(0).toISOString(),mastered:false}];return v;});await page.locator('[data-vocab-tab=review]').click();await page.locator('[data-review-word="0"]').click();assert.equal(await page.evaluate(()=>vocabGame.review),true);assert.equal(await page.locator('#vocabGameArea [data-vopt]').count(),4);const option=await page.evaluate(()=>vocabGame._opts.indexOf(vocabGame._answer));await page.locator('#vocabGameArea [data-vopt]').nth(option).click();assert.equal(await page.evaluate(()=>userState.vocabMistakes[0].mastered),true);await page.locator('[data-vocab-tab=review]').click();assert.equal(await page.locator('[data-review-word]').count(),0);await page.locator('[data-vocab-tab=words]').click();

 if(width<768){await page.locator('#mobileNavigation [data-shell-group="practice"]').click();assert.equal(await page.locator('#learningSidebar').isVisible(),true);await page.keyboard.press('Escape');assert.equal(await page.locator('#learningSidebar').isVisible(),false);assert.equal(await page.locator('#mobileNavigation [data-shell-group=tools]').getAttribute('aria-pressed'),'true');}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'shell overflow '+width);await page.screenshot({path:path.join(results,'grouped-navigation-'+width+'.png'),fullPage:true});
 await page.evaluate(json=>{userState=window.userState=JSON.parse(json);saveUserState(userState);localStorage.removeItem('igcseInterfaceLanguage');localStorage.setItem('igcseLangMode','bilingual');},source);
 await page.reload();if(width<768)await page.locator('#mobileNavigation [data-shell-group="dashboard"]').click();else await page.locator('#mainNav [data-shell-group="dashboard"]').click();
};
