const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 await page.locator('[data-page="page-resources"]').click();await page.locator('#srSubject').waitFor();
 const before=await page.evaluate(()=>JSON.stringify({mastery:window.userState.mastery,questionStats:window.userState.questionStats}));
 for(const subject of ['math','physics','chemistry','dt','business','computer_science','english']){await page.locator('#subjectSelect').selectOption(subject);assert.equal(await page.locator('#srSubject').inputValue(),subject);assert.ok(await page.locator('.sr-card').count()>0);}
 await page.locator('#srSubject').selectOption('all');await page.locator('#srIGCSE').check();assert.equal(await page.locator('.sr-card').count(),9);await page.locator('#srIGCSE').uncheck();assert.equal(await page.locator('.sr-card').count(),76);
 await page.locator('#srPricing').selectOption('free');assert.ok(await page.locator('.sr-card').count()>0);assert.ok((await page.locator('.sr-tags').allTextContents()).filter(s=>s.includes('来源费用')).every(s=>s.includes('来源费用：免费')));await page.locator('#srPricing').selectOption('all');
 await page.locator('#srSearch').fill('ZNotes');assert.equal(await page.locator('.sr-card').count(),1);assert.equal(await page.locator('.sr-actions a').getAttribute('rel'),'noopener noreferrer');
 await page.locator('#srSearch').fill('CIE Notes');await page.locator('#srSubject').selectOption('physics');const button=page.locator('[data-sr-save]');assert.match(await button.textContent(),/物理/);await button.click();assert.match(await page.locator('#srMessage').textContent(),/已收藏|已经在/);const count=await page.evaluate(()=>loadResources().physics.links.filter(x=>x.title==='CIE Notes').length);await button.click();assert.equal(await page.evaluate(()=>loadResources().physics.links.filter(x=>x.title==='CIE Notes').length),count);
 await page.reload();await page.locator('#srSearch').waitFor();assert.equal(await page.evaluate(()=>loadResources().physics.links.filter(x=>x.title==='CIE Notes').length),count);await page.locator('#subjectSelect').selectOption('physics');assert.ok((await page.locator('#myResources').textContent()).includes('CIE Notes'));
 await page.locator('#srSearch').fill('<img src=x onerror=alert(1)>');assert.equal(await page.locator('.sr-card').count(),0);assert.match(await page.locator('#srResults').textContent(),/没有符合/);assert.equal(await page.locator('#srResults img').count(),0);await page.locator('#srSearch').fill('');await page.locator('#srKind').selectOption('video');assert.ok(await page.locator('.sr-card').count()>0);await page.locator('#srKind').selectOption('all');
 assert.equal(await page.evaluate(()=>JSON.stringify({mastery:window.userState.mastery,questionStats:window.userState.questionStats})),before);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'resource mobile overflow '+width);await page.screenshot({path:path.join(results,'resources-'+width+'.png'),fullPage:true});await page.locator('#dashboard-nav').click();
};
