const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 const before=await page.evaluate(()=>JSON.stringify(userState));
 await page.evaluate(()=>{setCurrentSubjectSafe('math');IGCSE_CURRICULUM.setProfile('math',{qualification:'IGCSE',code:'0580',examYear:2027,foundation:false});switchPage('page-curriculum');});
 await page.locator('#schoolStatusFilter').waitFor();assert.equal(await page.locator('#examProfileDetails').getAttribute('open'),null);
 await page.locator('[data-browse-chapter]').selectOption('');assert.ok(await page.locator('[data-curriculum-topic]:visible').count()<=8);
 const row=page.locator('[data-curriculum-topic]:visible').first(),id=await row.getAttribute('data-curriculum-topic');await row.locator('[data-curriculum-status]').selectOption('current');await row.locator('[data-school-select]').check();
 await page.locator('#schoolNext').click();await page.locator('#schoolPrevious').click();assert.equal(await page.locator('[data-curriculum-topic="'+id+'"] [data-curriculum-status]').inputValue(),'current');
 await page.locator('#schoolBulkStatus').selectOption('taught');await page.locator('#schoolBulkApply').click();assert.equal(await page.evaluate(id=>IGCSE_CURRICULUM.status('math',id),id),'taught');
 await page.locator('#schoolStatusFilter').selectOption('taught');assert.ok(await page.locator('[data-curriculum-topic]:visible').evaluateAll(rows=>rows.every(r=>IGCSE_CURRICULUM.status('math',r.dataset.curriculumTopic)==='taught')));
 await page.locator('[data-curriculum-topic="'+id+'"] [data-curriculum-order]').fill('1');await page.locator('[data-curriculum-topic="'+id+'"] [data-curriculum-save]').click();assert.equal(await page.evaluate(id=>IGCSE_CURRICULUM.status('math',id),id),'taught');await page.screenshot({path:path.join(results,'school-workspace-'+width+'.png'),fullPage:true});
 await page.evaluate(id=>{userState.learnedTopics=userState.learnedTopics.filter(x=>x!==id);userState.openedTopics=[];switchPage('page-textbook');openTopic(IGCSE_CATALOG.topic('math',id));},id);
 assert.equal(await page.evaluate(id=>userState.learnedTopics.includes(id),id),false);const xp=await page.evaluate(()=>userState.xp);await page.locator('#markTopicRead').click();assert.equal(await page.evaluate(id=>userState.learnedTopics.includes(id),id),true);assert.equal(await page.evaluate(()=>userState.xp),xp+3);await page.locator('[data-topic-view="practice"]').click();await page.locator('#workspacePractice').click();await page.locator('#returnStudyTopic').click();assert.match(await page.locator('#topicStudyState').textContent(),/已读/);
 await page.screenshot({path:path.join(results,'topic-workspace-'+width+'.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 await page.evaluate(()=>switchPage('page-backup'));await page.locator('#wizardLearning').waitFor({state:'attached'});await page.locator('#separateBackupDetails > summary').click();const download=page.waitForEvent('download');await page.locator('#wizardLearning').click();assert.equal((await download).suggestedFilename(),'igcse-learning.json');
 await page.evaluate(()=>switchPage('page-writing'));await page.locator('#writingDraft').fill('My draft survives the new views.');if(width<768){await page.locator('[data-writing-view="model"]').click();assert.equal(await page.locator('#writingDraft').isVisible(),false);await page.locator('[data-writing-view="draft"]').click();assert.equal(await page.locator('#writingDraft').inputValue(),'My draft survives the new views.');}
 if(width<768){await page.locator('#mobileNavigation [data-shell-group=learn]').click();await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.getElementById('learningSidebar').contains(document.activeElement)),true);assert.equal(await page.evaluate(()=>document.querySelector('main').inert),true);await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.querySelector('main').inert),false);}
 await page.evaluate(before=>{const original=JSON.parse(before);for(const key of Object.keys(userState))delete userState[key];Object.assign(userState,original);saveUserState(userState);localStorage.removeItem('igcseWritingDrafts');},before);await page.reload();console.log('study flow '+width);
};
