const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 const before=await page.evaluate(()=>JSON.stringify(userState));await page.evaluate(()=>document.querySelector('[data-page=page-games]').click());assert.equal(await page.locator('#page-games.active').count(),1);
 await page.locator('[data-arcade-bank=computer_science]').click();assert.ok(await page.evaluate(()=>IGCSE_ARCADE.pool('choice').length)>20);await page.locator('[data-arcade-mode=choice]').click();assert.equal(await page.locator('[data-arcade-choice]').count(),4);await page.locator('[data-arcade-bank=cet4]').click();await page.locator('[data-arcade-mode=spell]').click();let v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);await page.locator('#arcadeAnswer').fill('wrong');await page.locator('.arcade-options button').first().click();assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().queue.length),11);assert.equal(await page.evaluate(v=>IGCSE_ARCADE.weak(v),v),true);await page.locator('#arcadeNext').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[1]);await page.locator('#arcadeHint').click();await page.locator('#arcadeAnswer').fill(v.en);await page.locator('.arcade-options button').first().click();assert.equal(await page.evaluate(v=>userState.vocabArcade.records[IGCSE_ARCADE.key(v)].stage,v),0);
 await page.locator('[data-arcade-mode=listen]').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);assert.match(await page.locator('#arcadeArea h3').textContent(),/_____/);await page.locator('#arcadeAnswer').fill(v.en);await page.locator('.arcade-options button').first().click();assert.match(await page.locator('#arcadeFeedback').textContent(),/正确/);
 await page.locator('[data-arcade-mode=grammar]').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);await page.locator('[data-arcade-choice]').filter({hasText:new RegExp('^'+v.answer+'$')}).click();assert.match(await page.locator('#arcadeFeedback').textContent(),/正确/);
 await page.locator('[data-arcade-mode=match]').click();const tiles=page.locator('.arcade-match button');const first=tiles.first(),id=await first.getAttribute('data-pair');await first.click();const matching=page.locator('.arcade-match button[data-pair="'+id+'"]');const side=await first.getAttribute('data-side');await page.locator('.arcade-match button[data-pair="'+id+'"][data-side="'+(side==='en'?'zh':'en')+'"]').click();assert.equal(await matching.first().isDisabled(),true);assert.equal(await matching.last().isDisabled(),true);
 await page.locator('[data-arcade-mode=duel]').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);await page.locator('[data-arcade-choice]').filter({hasText:new RegExp('^'+v.zh+'$')}).click();assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().right),1);
 await page.locator('#arcadeWeak').check();assert.ok(await page.evaluate(()=>IGCSE_ARCADE.pool('choice').every(IGCSE_ARCADE.weak)));await page.reload();assert.equal(await page.locator('#page-games.active').count(),1);assert.equal(await page.locator('[data-arcade-bank=cet4]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#arcadeWeak').isChecked(),true);assert.ok(await page.evaluate(()=>Object.keys(userState.vocabArcade.records).length)>0);
 await page.screenshot({path:path.join(results,'vocabulary-arcade-'+width+'.png'),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 await page.evaluate(before=>{const original=JSON.parse(before);for(const k of Object.keys(userState))delete userState[k];Object.assign(userState,original);saveUserState(userState);},before);await page.reload();console.log('vocabulary arcade '+width);
};
