const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results)=>{
 const before=await page.evaluate(()=>JSON.stringify(userState));await page.evaluate(()=>document.querySelector('[data-page=page-games]').click());assert.equal(await page.locator('#page-games.active').count(),1);
 await page.locator('[data-arcade-bank=computer_science]').click();assert.ok(await page.evaluate(()=>IGCSE_ARCADE.pool('choice').length)>20);await page.locator('[data-arcade-mode=choice]').click();assert.equal(await page.locator('[data-arcade-choice]').count(),4);
 await page.locator('[data-arcade-bank=cet4]').click();await page.locator('[data-arcade-mode=spell]').click();let v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);await page.locator('#arcadeAnswer').fill('wrong');await page.locator('#arcadeSubmit').click();assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().index),0);assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().queue.length),11);assert.match(await page.locator('#arcadeFeedback').textContent(),new RegExp(v.en));assert.equal(await page.locator('#arcadeAnswer').isDisabled(),false);await page.locator('#arcadeAnswer').fill(v.en);await page.locator('#arcadeSubmit').click();assert.equal(await page.locator('#arcadeFeedback').getAttribute('data-result'),'success');await page.waitForFunction(()=>IGCSE_ARCADE.getSession().index===1);assert.equal(await page.evaluate(v=>userState.vocabArcade.records[IGCSE_ARCADE.key(v)].stage,v),0);
 v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[1]);await page.locator('#arcadeHint').click();await page.locator('#arcadeAnswer').fill(v.en);await page.locator('#arcadeSubmit').click();await page.waitForFunction(()=>IGCSE_ARCADE.getSession().index===2);assert.equal(await page.evaluate(v=>userState.vocabArcade.records[IGCSE_ARCADE.key(v)].stage,v),0);
 await page.locator('[data-arcade-mode=listen]').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);assert.match(await page.locator('#arcadeArea h3').textContent(),/_____/);await page.evaluate(()=>{window.arcadeSavedSpeak=IGCSE_SPEECH.speak;IGCSE_SPEECH.speak=async text=>{window.arcadeSpoken=text;return {ok:true,american:true};};});await page.locator('.arcade-prompt .arcade-speak').click();assert.equal(await page.evaluate(()=>window.arcadeSpoken),v.sentence);await page.evaluate(()=>{IGCSE_SPEECH.speak=window.arcadeSavedSpeak;});await page.locator('#arcadeAnswer').fill('not-correct');await page.locator('#arcadeSubmit').click();assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().index),0);assert.match(await page.locator('#arcadeFeedback').textContent(),new RegExp(v.en));await page.screenshot({path:path.join(results,'vocabulary-retry-'+width+'.png'),fullPage:true});await page.locator('#arcadeAnswer').fill(v.en);await page.locator('#arcadeSubmit').click();await page.waitForFunction(()=>IGCSE_ARCADE.getSession().index===1);assert.equal(await page.evaluate(v=>userState.vocabArcade.records[IGCSE_ARCADE.key(v)].stage,v),0);
 await page.locator('[data-arcade-mode=grammar]').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);const wrong=page.locator('[data-arcade-choice]').filter({hasNotText:new RegExp('^'+v.answer+'$')}).first();await wrong.click();assert.equal(await wrong.getAttribute('data-result'),'error');assert.equal(await wrong.isDisabled(),true);assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().index),0);await page.locator('[data-arcade-choice]').filter({hasText:new RegExp('^'+v.answer+'$')}).click();await page.waitForFunction(()=>IGCSE_ARCADE.getSession().index===1);
 await page.locator('[data-arcade-mode=match]').click();const first=page.locator('.arcade-match [data-pair]').first(),id=await first.getAttribute('data-pair'),side=await first.getAttribute('data-side');assert.ok(await page.locator('.arcade-match .arcade-speak').count());await first.click();const matching=page.locator('.arcade-match [data-pair="'+id+'"]');await page.locator('.arcade-match [data-pair="'+id+'"][data-side="'+(side==='en'?'zh':'en')+'"]').click();assert.equal(await matching.first().isDisabled(),true);assert.equal(await matching.last().isDisabled(),true);assert.equal(await matching.first().getAttribute('data-result'),'success');
 for(const id of await page.locator('.arcade-match [data-pair][data-side=en]:not(:disabled)').evaluateAll(bs=>bs.map(b=>b.dataset.pair))){await page.locator('.arcade-match [data-pair="'+id+'"][data-side=en]').click();await page.locator('.arcade-match [data-pair="'+id+'"][data-side=zh]').click();}
 await page.locator('.arcade-result').waitFor();assert.equal(await page.locator('.arcade-stars .earned').count(),3);assert.match(await page.locator('.arcade-result-badges').textContent(),/配对达人/);const settled=await page.evaluate(()=>JSON.stringify(userState.vocabArcade.rewards));await page.evaluate(()=>IGCSE_ARCADE.result(IGCSE_ARCADE.getSession()));assert.equal(await page.evaluate(()=>JSON.stringify(userState.vocabArcade.rewards)),settled);await page.waitForTimeout(800);await page.locator('#arcadeArea').screenshot({path:path.join(results,'arcade-victory-'+width+'.png')});await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.arcade-confetti').evaluate(el=>getComputedStyle(el).display),'none');assert.equal(await page.locator('.arcade-result-trophy').evaluate(el=>getComputedStyle(el).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
 await page.locator('#arcadeReturn').click();assert.equal(await page.locator('.arcade-collection').count(),1);assert.match(await page.locator('.arcade-career').textContent(),/1 局完成/);

 await page.locator('[data-arcade-mode=duel]').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);await page.locator('[data-arcade-choice]').filter({hasText:new RegExp('^'+v.zh+'$')}).click();assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().right),1);await page.waitForFunction(()=>IGCSE_ARCADE.getSession().index===1);
 await page.locator('#arcadeSettings summary').click();await page.locator('#arcadeCountdown').selectOption('10');await page.locator('#arcadeEffects').uncheck();await page.locator('[data-arcade-mode=choice]').click();await page.locator('#arcadePause').click();await page.evaluate(()=>{IGCSE_ARCADE.getSession().remaining=1;});await page.waitForTimeout(300);assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().expired),false);await page.locator('#arcadePause').click();await page.waitForFunction(()=>IGCSE_ARCADE.getSession().expired);assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().index),0);assert.match(await page.locator('#arcadeFeedback').textContent(),/时间到/);await page.locator('#arcadeCountdown').selectOption('20');await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});IGCSE_ARCADE.getSession().remaining=15000;});await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession().remaining),15000);await page.evaluate(()=>{delete document.hidden;IGCSE_ARCADE.getSession().tickAt=Date.now()-60000;document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(300);assert.ok(await page.evaluate(()=>IGCSE_ARCADE.getSession().remaining)<15000);assert.ok(await page.evaluate(()=>IGCSE_ARCADE.getSession().remaining)>14000);await page.locator('#arcadeCountdown').selectOption('0');
 // Switching banks cancels an in-flight auto-advance so it cannot overwrite a new game.
 await page.locator('[data-arcade-mode=choice]').click();v=await page.evaluate(()=>IGCSE_ARCADE.getSession().queue[0]);await page.locator('[data-arcade-choice]').filter({hasText:new RegExp('^'+v.zh+'$')}).click();await page.locator('[data-arcade-bank=cet6]').click();await page.waitForTimeout(800);assert.equal(await page.evaluate(()=>IGCSE_ARCADE.getSession()),null);assert.equal(await page.locator('#arcadeAnswer').count(),0);
 await page.locator('[data-arcade-bank=cet4]').click();await page.locator('#arcadeWeak').check();await page.reload();assert.equal(await page.locator('#page-games.active').count(),1);assert.equal(await page.locator('[data-arcade-bank=cet4]').getAttribute('aria-pressed'),'true');assert.equal(await page.locator('#arcadeWeak').isChecked(),true);assert.ok(await page.evaluate(()=>Object.keys(userState.vocabArcade.records).length)>0);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);await page.screenshot({path:path.join(results,'vocabulary-arcade-'+width+'.png'),fullPage:true});await page.evaluate(before=>{IGCSE_ARCADE.stop();const original=JSON.parse(before);for(const k of Object.keys(userState))delete userState[k];Object.assign(userState,original);saveUserState(userState);},before);await page.reload();console.log('vocabulary arcade '+width);
};
