const assert=require('node:assert/strict'),path=require('node:path');
module.exports=async(page,width,results,expectedHTTP)=>{
 await page.route('**/api/ai/status',r=>r.fulfill({json:{configured:true,provider:'deepseek',model:'deepseek-flash'}}));await page.evaluate(()=>{setCurrentSubjectSafe('english');switchPage('page-textbook');openTopic(IGCSE_CATALOG.topic('english','eng_esl_writing'));});await page.locator('#topicWritingStudio').click();await page.locator('#writingGenre').waitFor();await page.waitForFunction(()=>!document.querySelector('[data-writing-mode="outline"]').disabled);
 const initial=await page.evaluate(()=>JSON.stringify({mastery:userState.mastery,topicStats:userState.topicStats,questionStats:userState.questionStats}));
 for(const genre of ['email','article','report','review','essay']){await page.locator('#writingGenre').selectOption(genre);assert.equal(await page.locator('.ws-example').count(),3);assert.match(await page.locator('#writingExample').textContent(),/原创教学示范/);}
 await page.locator('#writingGenre').selectOption('email');await page.locator('#writingDraft').fill('Yesterday I go to the park. It was enjoyable.');await page.reload();await page.locator('#writingDraft').waitFor();assert.equal(await page.locator('#writingDraft').inputValue(),'Yesterday I go to the park. It was enjoyable.');await page.waitForFunction(()=>!document.querySelector('[data-writing-mode="grammar"]').disabled);
 await page.route('**/api/writing/coach',r=>{const b=r.request().postDataJSON();assert.equal(b.genre,'email');assert.ok(!JSON.stringify(b).includes('API_KEY'));return r.fulfill({json:{summary:'检查过去时 <img src=x onerror=alert(1)>',outline:b.mode==='outline'?['开头：说明目的','主体：描述经历','结尾：邀请朋友']:[],hints:['先检查时间标志词'],corrections:b.mode==='grammar'?[{original:'I go',replacement:'I went',explanation:'Yesterday 对应过去时。'}]:[],ignoredCorrections:0}});});
 await page.locator('[data-writing-mode="outline"]').click();await page.locator('#writingAIStatus').filter({hasText:'建议已生成'}).waitFor();assert.match(await page.locator('#writingFeedback').textContent(),/提纲参考/);assert.equal(await page.locator('#writingFeedback img').count(),0);assert.equal(await page.locator('#writingDraft').inputValue(),'Yesterday I go to the park. It was enjoyable.');
 await page.locator('[data-writing-mode="hint"]').click();await page.locator('#writingAIStatus').filter({hasText:'建议已生成'}).waitFor();assert.match(await page.locator('#writingFeedback').textContent(),/时间标志词/);
 await page.locator('[data-writing-mode="grammar"]').click();await page.locator('[data-writing-apply]').waitFor();await page.locator('#writingDraft').fill('Yesterday I go to the park. I wrote more.');assert.equal(await page.locator('[data-writing-apply]').isDisabled(),true);await page.locator('[data-writing-mode="grammar"]').click();await page.waitForFunction(()=>!document.querySelector('[data-writing-apply]').disabled);await page.locator('[data-writing-apply]').click();assert.match(await page.locator('#writingDraft').inputValue(),/I went/);await page.locator('#writingUndo').click();assert.match(await page.locator('#writingDraft').inputValue(),/I go/);
 await page.locator('#writingGenre').selectOption('article');assert.equal(await page.locator('#writingDraft').inputValue(),'');await page.locator('#writingGenre').selectOption('email');assert.match(await page.locator('#writingDraft').inputValue(),/I go/);
 expectedHTTP.add('502 '+new URL('/api/writing/coach',page.url()).href);await page.route('**/api/writing/coach',r=>r.fulfill({status:502,json:{error:'测试服务暂不可用'}}));await page.locator('[data-writing-mode="hint"]').click();await page.locator('#writingAIStatus').filter({hasText:'测试服务暂不可用'}).waitFor();assert.match(await page.locator('#writingDraft').inputValue(),/I go/);
 assert.equal(await page.evaluate(()=>JSON.stringify({mastery:userState.mastery,topicStats:userState.topicStats,questionStats:userState.questionStats})),initial);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'writing overflow '+width);await page.screenshot({path:path.join(results,'writing-'+width+'.png'),fullPage:true});await page.unroute('**/api/writing/coach');await page.locator('#dashboard-nav').click();
};
